# Generated by Django 4.2.7 on 2023-11-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='isbn',
            field=models.CharField(max_length=30),
        ),
    ]
